export const smiths = {
  stage: 8,
  methods: [
    'Ashtead',
    'Bristol',
    'Cambridge',
    'Cassiobury',
    'Cornwall',
    'Cray',
    'Double Dublin',
    'Glasgow',
    'Ipswich',
    'Jersey',
    'Lincolnshire',
    'Lindum',
    'London',
    'Preston',
    'Pudsey',
    'Rutland',
    'Superlative',
    'Tavistock',
    'Uxbridge',
    'Watford',
    'Wembley',
    'Whalley',
    'Yorkshire',
  ],
};
